name: Manual Station Update

on:
  workflow_dispatch:
  #schedule:
    #- cron: '50 4 * * *'   # 10:20 AM IST
    #- cron: '50 11 * * *'  # 5:20 PM IST

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pillow

      - name: Keep only last 3 JSON files
        run: |
          ls -t status_all_*.json 2>/dev/null | tail -n +4 | xargs -r rm --

      - name: Run script
        run: python get_mausam_rdr_img_status.py

      - name: Copy latest file
        run: |
          LATEST=$(ls -t status_all_*.json | head -n 1)
          cp "$LATEST" status_all_latest.json

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add status_all_*.json status_all_latest.json
          git commit -m "Scheduled update" || echo "No changes to commit"
          git push origin main
